In [9]:
# What is the shape of the following array?
# Answer: The first element of the tuple is the number of 
# rows, the second is the number of columns
import numpy as np

A=np.array([[1,0,1],[0,1,1]])
print(A.shape)

(2, 3)


In [10]:
# Consider the following array
# What is the value in A[0,1]?
# Answer: First row, second column = 0

A=np.array([[1,0,1],[2,2,2]])
A[0,1]

0

In [13]:
# Add two arrays in numpy
# Equivalent to matrix addition 
import numpy as np

X = np.array([[1,0],[0,1]])
Y = np.array([[2,1],[1,2]])
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [16]:
# What is the result of the following operation?
# Multiplying the array by 2 doubles each element
Y=np.array([[2,1],[1,2]])
Z=2*Y
Z

array([[4, 2],
       [2, 4]])

In [18]:
# Find the products of two arrays in one line
X = np.array([[1,0], [0,1]])
Y = np.array([[2,1], [1,2]])
Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [19]:
# Find the dot product of the matrices
A = np.array([[0,1,1],[1,0,1]])
B = np.array([[1,1],[1,1],[-1,1]])
C = np.dot(A,B)
C

array([[0, 2],
       [0, 2]])

In [20]:
# Create a 2D Numpy Array
# import the libraries

import numpy as np
import matplotlib.pyplot as plt

In [21]:
# Consider the list a, the list contains 3 nested lists each
# of equal size.
# Create a list

a = [[11,12,13], [21,22,23], [31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [22]:
# Case the list to a Numpy Array as follow
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [23]:
# Use the attribute ndim to obtain the number of axes or
# dimensions referred to as the rank
# Show the numpy array dimensions

A.ndim

2

In [24]:
# Attribute shape returns a tuple corresponding to the size
# or number of each dimension.
# Show the numpy array shape

A.shape

(3, 3)

In [25]:
# The total number of elements in the array is give by the
# attribute size.
# Show the numpy array size

A.size

9

In [26]:
# Accessing Different Elements of a Numpy Array
# Access the element on the second row and third column

A[1,2]

23

In [28]:
# Access the element on the first row and first column

A[0][0]

11

In [29]:
# Access the element on the first and first and second 
# columns

A[0][0:2]

array([11, 12])

In [31]:
# We can obtain the last 2 rows of the 3rd column as 
# follows:
# Access the element on the first and second rows and third
# column

A[1:3,2]

array([23, 33])

In [32]:
# Create a numpy array X

X = np.array([[1,0], [0,1]])
X

array([[1, 0],
       [0, 1]])

In [33]:
# Create a numpy array Y

Y = np.array([[2,1],[1,2]])
Y

array([[2, 1],
       [1, 2]])

In [34]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [35]:
# Multiplying a numpy array by a scaler is identical to 
# multiplying a matrix by a scaler. If we multiply Y by 
# the scaler 2, we simply multiply every element in the 
# matrix by 2 as shown in the figure.
# Create a numpy array Y

Y = np.array([[2,1],[1,2]])
Y

array([[2, 1],
       [1, 2]])

In [36]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [37]:
# Create a numpy array Y

Y = np.array([[2,1],[1,2]])
Y

array([[2, 1],
       [1, 2]])

In [38]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [39]:
# Create a numpy array Y

Y = np.array([[2,1],[1,2]])
Y

array([[2, 1],
       [1, 2]])

In [40]:
# Create a numpy array X

X = np.array([[1,0],[0,1]])
X

array([[1, 0],
       [0, 1]])

In [41]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [44]:
# Define matrix A and B:
# Create a matrix A 

A = np.array([[0,1,1],[1,0,1]])
A


array([[ 1,  1],
       [-1,  1]])

In [46]:
# Create a matrix B

B = np.array([[1,1],[1,1],[-1,1]])
B             

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [50]:
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [52]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [48]:
# We use the numpy attribute T to calculate the transposed
# matrix.
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [49]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])